arm_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - base_link_to_base_yaw_link_joint
    - base_yaw_link_to_first_link_joint

  gains: # Required because we're controlling a velocity interface
    base_link_to_base_yaw_link_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
    base_yaw_link_to_first_link_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}